### ISSUE TITLE
problems loading 70747ned

### ISSUE THREAD

**Issue by maesser** [edwindj/cbsodata.R#17]
Hi,

I'am having problems with loading the 70747ned table, other tables seem to be alright. When I try to get the table I get the following:

Attempt 1
code:
fname = "70747ned"
bucket1 <- cbs_get_data(id = fname)

Output:

Error: parse error: premature EOF { "odata.metadata":"https:// (right here) ------^ In addition: Warning message: In fun(libname, pkgname) : couldn't connect to display ":0"

Attempt 2
code:
fname = "70747ned"
cbs_download_table(id=fname, dir=fname)

output:

[1] "https://opendata.cbs.nl/ODataFeed/odata/70747ned/UntypedDataSet?$format=json&$skip=7060000"
Writing...
Reading...
[1] "https://opendata.cbs.nl/ODataFeed/odata/70747ned/UntypedDataSet?$format=json&$skip=7070000"
Error: parse error: premature EOF
                                       {    "odata.metadata":"https://
                     (right here) ------^

Regards,

Maarten.

**Comment by edwindj** [comment]
Thanks for reporting:
I tried your code, but that works for me (these are the most nasty bugs...), so it can be any of the following:
- A glitch in the data (not probable)
- A glitch in the internet connection: the data your are downloading is quite large, so it may be that your internet connection is interrupted during the download. You could try to restrict the amount of data by filter statement (see the vignette for an example).
 
- Can you try to execute the command with the extra parameter `verbose = TRUE`? This will print more detailed information on the downloading of the data.
- Did you try the latest version of cbsodataR? You could try to use `devtools::install_github`

**Comment by maesser** [comment]
It seems you were exactly right, I had the latest version from CRAN. This version generates an error, however after installing the latest version directly from GitHub the table is looking like it is loading completely.

Thank you for your help and your quick response!

**Comment by maesser** [comment]
I was bit quick to close this issue, it seems the problem still exists,

fname = "70747ned"
cbs_download_table(id=fname, dir=fname, verbose=TRUE)

[1] "https://opendata.cbs.nl/ODataFeed/odata/70747ned/UntypedDataSet?$format=json&$skip=11270000"
Writing...
Reading...
[1] "https://opendata.cbs.nl/ODataFeed/odata/70747ned/UntypedDataSet?$format=json&$skip=11280000"
Error in parse_con(txt, bigint_as_char) : parse error: premature EOF
                                       
                     (right here) ------^
In addition: Warning message:
closing unused connection 3 (/tmp/RtmpYgrGGk/data.csv) 

I am using version 0.3.1.9000 from GitHub.

It does get further in the proces but it still does not complete getting the full table.

**Comment by edwindj** [comment]
Sorry to hear that: the problem is not easily solved: it seems that during the download the connection was interupted. (premature EOF means "premature end of file"). This is not due to `cbsodataR` but to the internet service receiving and delivering the data. I can add a retry if the connection is interrupted, but that is only a simple band aid. I suggest restricting the data query e.g. by using `Perioden=2017JJ00` and download the data for several year separately.

**Comment by maesser** [comment]
But when I run it like bellow in small batches, is still get the same problems. Other tables are no problem.

> bucket2015 <- cbs_get_data(id = fname, Periods="2015JJ00")
Error in parse_con(txt, bigint_as_char) : parse error: premature EOF
                                       
                     (right here) ------^
In addition: Warning message:
In .Internal(vapply(X, FUN, FUN.VALUE, USE.NAMES)) :
  closing unused connection 3 (/tmp/RtmpYgrGGk/data.csv)
> bucket2016 <- cbs_get_data(id = fname, Periods="2016JJ00")
Error in parse_con(txt, bigint_as_char) : parse error: premature EOF
                                       
                     (right here) ------^
In addition: Warning message:
closing unused connection 4 (/tmp/RtmpYgrGGk/data.csv) 
> bucket2017 <- cbs_get_data(id = fname, Periods="2017JJ00")
Error in parse_con(txt, bigint_as_char) : parse error: premature EOF
                                       
                     (right here) ------^
In addition: Warning message:
In .Internal(vapply(X, FUN, FUN.VALUE, USE.NAMES)) :
  closing unused connection 3 (/tmp/RtmpYgrGGk/data.csv)

Also when using the other function:

cbs_download_table(id = fname, Periods="2015JJ00")

[1] "https://opendata.cbs.nl/ODataFeed/odata/70747ned/UntypedDataSet?$format=json&$filter=%28Periods%20eq%20%272015JJ00%27%29&$skip=8010000"
Writing...
Reading...
[1] "https://opendata.cbs.nl/ODataFeed/odata/70747ned/UntypedDataSet?$format=json&$filter=%28Periods%20eq%20%272015JJ00%27%29&$skip=8020000"
Error in parse_con(txt, bigint_as_char) : parse error: premature EOF
                                       
                     (right here) ------^

**Comment by edwindj** [comment]
It is a rather big table you are trying to download (> 3M rows). It seems that the internet connection is not as stable as one would like it to be. One option is to further partition the data, e.g. by age as in the following script. That allows one to download portions. 


```r 
library(cbsodataR)

toc <- cbs_get_toc()
id <- '70747ned'
m <- cbs_get_meta(id)
View(m$Leeftijd)

for (age in m$Leeftijd$Key){
  # may be add a tryCatch 
  dat <- cbs_get_data('70747ned', Leeftijd = age, verbose=TRUE)
  # do some extra stuff..
  #
  filename <- paste0("70747ned_", age ,".csv")
  write.csv(dat, filename, row.names = FALSE, na = "")
}
```

PS : I am trying to adapt the code of cbsodataR so that it will retry to download when the connection is failing, but it more difficult (also to test)

**Comment by J535D165** [comment]
I do have the same issue with this table. I'm using a (fast and stable) university network to download the data. I think table '47015NED' gives similar problems. 

With the Python library, these tables result in errors as well. Check issue https://github.com/J535D165/cbsodata/issues/5. The error is more informative. Error 54 means "Connection reset by peer" http://www.ioplex.com/~miallen/errcmpp.html. https://stackoverflow.com/questions/1434451/what-does-connection-reset-by-peer-mean. I do have another user with this problem for some tables.

**Comment by edwindj** [comment]
Thanks for the info! 
I will contact the maintainers of the OData webservice and ask them to find out what is happening. (maybe the webserver is dropping connections or something similar).

**Comment by maesser** [comment]
Just to cover all my bases, tried this(see below) on my own connection(my home internet line) outside the organization with version 0.3.1.9000. Same problem.

cbs_download_table(id=fname, Periods="2015JJ00")

[1] "https://opendata.cbs.nl/ODataFeed/odata/70747ned/UntypedDataSet?$format=json&$filter=%28Periods%20eq%20%272015JJ00%27%29&$skip=5040000"
Writing...
Reading...
[1] "https://opendata.cbs.nl/ODataFeed/odata/70747ned/UntypedDataSet?$format=json&$filter=%28Periods%20eq%20%272015JJ00%27%29&$skip=5050000"
Error in parse_con(txt, bigint_as_char) : parse error: premature EOF
                                       
                     (right here) ------^

And Thanks Edwin for all your help

**Comment by edwindj** [comment]
In contact with technical people maintaining the OData webservice: they would like to know at what time/date the request failed, that makes it easier to find out on the webserver what went wrong. (maybe look at modification file date of the files downloaded?)

**Comment by edwindj** [comment]
Maintainers of webservice think it has to do with the load balancing of the webservice (the technical stack seems a bit complicated) and don't have a immediate fix for the issue. 

@maesser I have added a retry method: when something went wrong with the connection, it will retry to load the current chunk and move on. Hopefully this will do the trick. (let me know :-) )

**Comment by maesser** [comment]
The time of my last attempt was 2018-12-04 11:54:19.762791027 this is at least the time the data file was last modified by the cbs commands.

**Comment by edwindj** [comment]
@maesser Can you do another

```r
devtools::install_github("edwindj/cbsodataR")
```
 and check if this works for your?

Best,

Edwin

**Comment by maesser** [comment]
@edwindj I was already running my code, so far so good but it wasn't finished yet :)

I will let you now when it is done.

**Comment by maesser** [comment]
It does get a lot further in the proces but comes to a silent standstill at some point.

I started the full download around 7:00 in the morning and was getting the data bit by bit but stopped adding data at,

2202329088 2018-12-06 13:58:21.174385607 +0100 data.csv

R Does not recognize failure and comes to a standstill with the following,

https://opendata.cbs.nl/ODataFeed/odata/70747ned/UntypedDataSet?$format=json&$skip=29820000Writing...
Reading...
https://opendata.cbs.nl/ODataFeed/odata/70747ned/UntypedDataSet?$format=json&$skip=29830000Writing...
Reading...
https://opendata.cbs.nl/ODataFeed/odata/70747ned/UntypedDataSet?$format=json&$skip=29840000Writing...
Reading...
https://opendata.cbs.nl/ODataFeed/odata/70747ned/UntypedDataSet?$format=json&$skip=29850000

It has stayed this way up to this morning.(cancelled the proces) 

After cancel/kill it gave the following errors:

Warning messages:
1: Failing: https://opendata.cbs.nl/ODataFeed/odata/70747ned/UntypedDataSet?$format=json&$skip=8210000
Retrying... 
2: Failing: https://opendata.cbs.nl/ODataFeed/odata/70747ned/UntypedDataSet?$format=json&$skip=8800000
Retrying... 
3: Failing: https://opendata.cbs.nl/ODataFeed/odata/70747ned/UntypedDataSet?$format=json&$skip=24500000
Retrying... 
4: Failing: https://opendata.cbs.nl/ODataFeed/odata/70747ned/UntypedDataSet?$format=json&$skip=27530000
Retrying...  

Today I will try doing year by year again.

**Comment by maesser** [comment]
Tested a smaller tabel which seems to have the same problem(using latest version):

 tbl_cbs_id = "03742"
 cbs_download_table(id = tbl_cbs_id)

https://opendata.cbs.nl/ODataFeed/odata/03742/UntypedDataSet?$format=json&$skip=9760000Writing...
Reading...
https://opendata.cbs.nl/ODataFeed/odata/03742/UntypedDataSet?$format=json&$skip=9770000Writing...
Reading...
https://opendata.cbs.nl/ODataFeed/odata/03742/UntypedDataSet?$format=json&$skip=9780000Writing...
Reading...
https://opendata.cbs.nl/ODataFeed/odata/03742/UntypedDataSet?$format=json&$skip=9790000Writing...
Done!
Warning messages:
1: In .Internal(vapply(X, FUN, FUN.VALUE, USE.NAMES)) :
  closing unused connection 4 (/tmp/RtmpYd7qwc/data.csv)
2: Failing: https://opendata.cbs.nl/ODataFeed/odata/03742/UntypedDataSet?$format=json&$skip=2480000
Retrying... 
3: Failing: https://opendata.cbs.nl/ODataFeed/odata/03742/UntypedDataSet?$format=json&$skip=8670000
Retrying... 
4: Failing: https://opendata.cbs.nl/ODataFeed/odata/03742/UntypedDataSet?$format=json&$skip=8970000
Retrying...

**Comment by maesser** [comment]
After a few more tries I got 70747 in, the retry works. Thanks @edwindj for your help!

One quick question, will CBS fix the underlying problem?

**Comment by edwindj** [comment]
Thanks for reporting and glad it worked for you!

CBS fixing it: 
- I reported it and they are looking at it. It seems a complicated configuration thingy. I will 

They are working on a new implementation (odata4) of the OpenData API:
- different data layout, so only table cells with data are downloaded
- HTTP compression
- and a bulk download (csv)

These options will probably fix current problems.

**Comment by maesser** [comment]
Yes that would be great.

For now, thanks for the help.
