### ISSUE TITLE
please document output values

### ISSUE THREAD

**Issue by markvanderloo** [edwindj/cbsodata.R#21]
The help documentation is pretty thin. It could be greatly improved by added a few lines in the `@description` section and adding at a `@return` everywhere.

**Comment by edwindj** [comment]
Thx! Most can be found in the vignette, Will add documentation, but returned result stays close to result of API (which IMHO is not optimal).

**Comment by edwindj** [comment]
Wondering which method you specifically mean, because most methods do have a documented return value. Guessing that it is `cbs_get_meta`? Working on that one.

**Comment by edwindj** [comment]
improved the documentation a lot (> 0.3.2)
