### ISSUE TITLE
cbs_get_meta() gives error: fixed but not yet on CRAN

### ISSUE THREAD

**Issue by gsverhoeven** [edwindj/cbsodata.R#23]
Hi!

I ran into the `cbs_get_meta()` error (``Error in strsplit(params$`$select`, ", ") : non-character argument`` ) that was reported and fixed by @sarahouweling a few days ago.
The CRAN version is not yet updated, so the solution for now is to install from github.

`devtools::install_github("edwindj/cbsodataR")`

Thanks for creating this awesome package!

**Comment by edwindj** [comment]
Thx for reporting! I tried uploading on CRAN, but CRAN-maintainers are this week on (much deserved) holiday.
Will be fixed next week.

**Comment by edwindj** [comment]
On its way to CRAN (windows version will be available within 24 hours)
