### ISSUE TITLE
week periods are not converted with `cbs_add_date_column`

### ISSUE THREAD

**Issue by RichardFromHolland** [edwindj/cbsodata.R#25]
Converting the cbs date to the regular date format does not seem to work:

-----------code snippet----------------
library(cbsodataR)

dt <- cbs_get_data("70895ned")
dt <- cbs_add_date_column (dt)

head (dt)
-----------output----------------
  Geslacht LeeftijdOp31December Perioden Perioden_Date Perioden_freq Overledenen_1
1     1100                10000 1995X000          <NA>          <NA>           394
2     1100                10000 1995W101          <NA>          <NA>          2719
3     1100                10000 1995W102          <NA>          <NA>          2823
4     1100                10000 1995W103          <NA>          <NA>          2609
5     1100                10000 1995W104          <NA>          <NA>          2664
6     1100                10000 1995W105          <NA>          <NA>          2577
-----------end-----------------

The code did add the colums but it did not fill in the correct date and the correct frequency. 
n.b.: Not shown here is that in case of a year-date, it is filled in correctly for both.

**Comment by RichardFromHolland** [comment]
In the output above, originally it included the missing NA as colums. However, this was omitted by the editor of github (?!?!). Very strange. Please run the code in RStudio, it is self explaining.

**Comment by edwindj** [comment]
Thanks for reporting and sorry for my late reply (a bit busy)!
This is a missing feature currently: week conversions are not (yet) supported in `cbsodataR`. I will try to add it asap.

**Comment by edwindj** [comment]
The development version of cbsodataR should do the trick:

```
devtools::install_github("edwindj/cbsodataR")
```
Can you report if this is working for you? I will then upload a new version to CRAN.

Best,

**Comment by edwindj** [comment]
You can reopen it, if it is not working
