### ISSUE TITLE
setwd() in package limits cronjobs

### ISSUE THREAD

**Issue by abjeroen** [edwindj/cbsodata.R#28]
Hi Edwindj, 

Als ik mijn R script via de terminal wil starten (ipv via Rstudio), dan krijg ik de melding dat setwd() afgetrapt wordt in het package. Dit mag niet via terminal scripts. Kun je de paden dynamisch maken, zodat je niet afhankelijk bent van setwd()?

Het zit 'm in cbs_download_meta.R

**Comment by edwindj** [comment]
Thx! I ga er naar kijken.

**Comment by edwindj** [comment]
Does the latest version github solve your problem?
_

**Comment by abjeroen** [comment]
👍  yes. Thanks for responding this quickly!

**Comment by edwindj** [comment]
Onderweg naar CRAN / on its way to CRAN
