### ISSUE TITLE
method to keep track of table updates?

### ISSUE THREAD

**Issue by jessekps** [edwindj/cbsodata.R#36]
This is a feature request, not a bug I think.

Use case: I am interested in table 85067NED, "Gebieden in Nederland"

```
library(cbsodataR)
library(dplyr)

toc = cbs_get_toc()
filter(toc, Identifier=='85067NED') |> select(Identifier, Title, Period)

  Identifier Title                      Period
  <chr>      <chr>                      <chr> 
1 85067NED   Gebieden in Nederland 2022 2022  
``` 
However, newer versions of the table may become available and I would like to always get the most recent version. I don't see any pattern to the Identifier of this table and previous versions. I thought `cbs_search` might do the trick but it returns only one version of the table and that is an old one.

```
s=cbs_search('gebieden in nederland',language='nl')
select(s, Title, Identifier, Period)

   Title                                                                         Identifier Period                            
   <chr>                                                                         <chr>      <chr>                             
 1 "Regionale kerncijfers Nederland"                                             70072ned   Jaarcijfers 1995 - 2023           
 2 "Conjunctuurenquête Nederland; kwartaal, bedrijfstakken"                      82435NED   1e kwartaal 2012 - 1e kwartaal 20…
 3 "Banen van werknemers in december; economische activiteit (SBI2008), regio"   83582NED   2010-2021                         
 4 "Bevolkingsontwikkeling; regio per maand"                                     37230ned   Januari 2002 - maart 2023         
 5 "Bedrijven; bedrijfstak"                                                      81589NED   2007 kwI - 2023 kw II             
 6 "Winning, invoer en uitvoer van materialen naar soort; nationale rekeningen " 83180NED   1996-2020                         
 7 "Bodemgebruik; uitgebreide gebruiksvorm, per gemeente"                        70262ned   1996, 2000, 2003, 2006, 2008, 201…
 8 "Winning, invoer en uitvoer materialen per continent; nationale rekeningen"   83177NED   2004-2020                         
 9 "Onderwijsinstellingen; grootte, soort, levensbeschouwelijke grondslag"       03753      1990/'91 - 2021/'22               
10 "Gebieden in Nederland 2020"                                                  84721NED   2020        
```

So my request: is there a way, or could there be a way, in which I can get the most recent version of a specific table? And a second note: it is not clear to me from the help where `cbs_search` actually searches. Apparently not in the title or it would have found the most recent version as well.

Many thanks for the package by the way, it greatly simplifies things.

**Comment by edwindj** [comment]
Thanks for your question! Sorry for the delayed reply, I completely missed your question.

Regarding the question(s) you asked:

- as you noticed the table(s) you are looking for are not organized as one table, but for each year a separate table. Technically these tables are independent and not "aware" of the tables for other years: they all have a different identifier.

- the easiest way of dealing with this is searching the `toc` or equivalent the `datasets` for the table title. Something like this:



``` r
library(cbsodataR)
library(dplyr)
library(stringr)

datasets <- cbs_get_datasets()

datasets |> 
  filter(str_detect(Title, "Gebieden in")) |> 
  select(Updated, Identifier, Title)
```

    # A tibble: 29 × 3
       Updated             Identifier Title                     
       <dttm>              <chr>      <chr>                     
     1 2024-03-20 00:00:00 85755NED   Gebieden in Nederland 2024
     2 2023-06-07 00:00:00 85385NED   Gebieden in Nederland 2023
     3 2022-08-23 00:00:00 85067NED   Gebieden in Nederland 2022
     4 2022-01-14 00:00:00 84929NED   Gebieden in Nederland 2021
     5 2021-10-11 00:00:00 84721NED   Gebieden in Nederland 2020
     6 2021-02-26 00:00:00 84378NED   Gebieden in Nederland 2019
     7 2021-02-26 00:00:00 83859NED   Gebieden in Nederland 2018
     8 2018-03-07 00:00:00 83553NED   Gebieden in Nederland 2017
     9 2018-03-07 00:00:00 83287NED   Gebieden in Nederland 2016
    10 2020-12-18 00:00:00 82949NED   Gebieden in Nederland 2015
    # ℹ 19 more rows
- `cbs_search` uses the search engine of CBS to search for words (or synonyms) in **all** text of a table, not just the title.

I hope this helps,

Best,

Edwin
